[project]
name = "meetgist-ai-powered-meeting-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "assemblyai",
    "fastapi",
    "pydantic",
    "python-dotenv",
    "pyyaml",
    "streamlit",
    "supabase",
    "uvicorn",
]
